/**
 * Calendario y grupos oficiales del Mundial FIFA 2026 (48 equipos, partidos 1–72).
 * Fuentes: páginas de Wikipedia por grupo (alineadas con FIFA Match Centre) y
 * https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_knockout_stage para cruces 73–104.
 * Re-ejecuta `npm run seed` tras un reset de base de datos.
 */

export type HostCountry = "USA" | "CAN" | "MEX";

/** Suma horas locales + offset = UTC (junio 2026: sin DST en la mayor parte de México = UTC−6). */
export type TzKey = "MEX" | "EDT" | "CDT" | "PDT";

const TZ_ADD: Record<TzKey, number> = {
  MEX: 6,
  EDT: 4,
  CDT: 5,
  PDT: 7,
};

export function localToUtcIso(
  dateYmd: string,
  hour: number,
  minute: number,
  tz: TzKey
): string {
  const [y, m, d] = dateYmd.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d, hour + TZ_ADD[tz], minute, 0)).toISOString();
}

export type WcTeam = {
  name: string;
  name_en: string;
  code: string;
  group_letter: string;
};

export const WC2026_TEAMS: WcTeam[] = [
  { name: "México", name_en: "Mexico", code: "mx", group_letter: "A" },
  { name: "Sudáfrica", name_en: "South Africa", code: "za", group_letter: "A" },
  { name: "Corea del Sur", name_en: "South Korea", code: "kr", group_letter: "A" },
  { name: "República Checa", name_en: "Czech Republic", code: "cz", group_letter: "A" },
  { name: "Canadá", name_en: "Canada", code: "ca", group_letter: "B" },
  { name: "Bosnia y Herzegovina", name_en: "Bosnia and Herzegovina", code: "ba", group_letter: "B" },
  { name: "Catar", name_en: "Qatar", code: "qa", group_letter: "B" },
  { name: "Suiza", name_en: "Switzerland", code: "ch", group_letter: "B" },
  { name: "Brasil", name_en: "Brazil", code: "br", group_letter: "C" },
  { name: "Marruecos", name_en: "Morocco", code: "ma", group_letter: "C" },
  { name: "Haití", name_en: "Haiti", code: "ht", group_letter: "C" },
  { name: "Escocia", name_en: "Scotland", code: "gb-sct", group_letter: "C" },
  { name: "Estados Unidos", name_en: "United States", code: "us", group_letter: "D" },
  { name: "Paraguay", name_en: "Paraguay", code: "py", group_letter: "D" },
  { name: "Australia", name_en: "Australia", code: "au", group_letter: "D" },
  { name: "Turquía", name_en: "Turkey", code: "tr", group_letter: "D" },
  { name: "Alemania", name_en: "Germany", code: "de", group_letter: "E" },
  { name: "Curazao", name_en: "Curaçao", code: "cw", group_letter: "E" },
  { name: "Costa de Marfil", name_en: "Ivory Coast", code: "ci", group_letter: "E" },
  { name: "Ecuador", name_en: "Ecuador", code: "ec", group_letter: "E" },
  { name: "Países Bajos", name_en: "Netherlands", code: "nl", group_letter: "F" },
  { name: "Japón", name_en: "Japan", code: "jp", group_letter: "F" },
  { name: "Suecia", name_en: "Sweden", code: "se", group_letter: "F" },
  { name: "Túnez", name_en: "Tunisia", code: "tn", group_letter: "F" },
  { name: "Bélgica", name_en: "Belgium", code: "be", group_letter: "G" },
  { name: "Egipto", name_en: "Egypt", code: "eg", group_letter: "G" },
  { name: "Irán", name_en: "Iran", code: "ir", group_letter: "G" },
  { name: "Nueva Zelanda", name_en: "New Zealand", code: "nz", group_letter: "G" },
  { name: "España", name_en: "Spain", code: "es", group_letter: "H" },
  { name: "Cabo Verde", name_en: "Cape Verde", code: "cv", group_letter: "H" },
  { name: "Arabia Saudita", name_en: "Saudi Arabia", code: "sa", group_letter: "H" },
  { name: "Uruguay", name_en: "Uruguay", code: "uy", group_letter: "H" },
  { name: "Francia", name_en: "France", code: "fr", group_letter: "I" },
  { name: "Senegal", name_en: "Senegal", code: "sn", group_letter: "I" },
  { name: "Irak", name_en: "Iraq", code: "iq", group_letter: "I" },
  { name: "Noruega", name_en: "Norway", code: "no", group_letter: "I" },
  { name: "Argentina", name_en: "Argentina", code: "ar", group_letter: "J" },
  { name: "Argelia", name_en: "Algeria", code: "dz", group_letter: "J" },
  { name: "Austria", name_en: "Austria", code: "at", group_letter: "J" },
  { name: "Jordania", name_en: "Jordan", code: "jo", group_letter: "J" },
  { name: "Portugal", name_en: "Portugal", code: "pt", group_letter: "K" },
  { name: "RD Congo", name_en: "DR Congo", code: "cd", group_letter: "K" },
  { name: "Uzbekistán", name_en: "Uzbekistan", code: "uz", group_letter: "K" },
  { name: "Colombia", name_en: "Colombia", code: "co", group_letter: "K" },
  { name: "Inglaterra", name_en: "England", code: "gb-eng", group_letter: "L" },
  { name: "Croacia", name_en: "Croatia", code: "hr", group_letter: "L" },
  { name: "Ghana", name_en: "Ghana", code: "gh", group_letter: "L" },
  { name: "Panamá", name_en: "Panama", code: "pa", group_letter: "L" },
];

export type GroupMatchDef = {
  match_number: number;
  group_letter: string;
  home_code: string;
  away_code: string;
  match_date: string;
  venue: string;
  city: string;
  country_host: HostCountry;
};

/**
 * Horas locales según Wikipedia / FIFA donde constan; el resto 15:00 hora local del estadio.
 * Zona: MEX (UTC−6), EDT, CDT, PDT.
 */
export const WC2026_GROUP_MATCHES: GroupMatchDef[] = [
  // A
  {
    match_number: 1,
    group_letter: "A",
    home_code: "mx",
    away_code: "za",
    match_date: localToUtcIso("2026-06-11", 12, 0, "MEX"),
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country_host: "MEX",
  },
  {
    match_number: 2,
    group_letter: "A",
    home_code: "kr",
    away_code: "cz",
    match_date: localToUtcIso("2026-06-11", 21, 0, "MEX"),
    venue: "Estadio Akron",
    city: "Zapopan",
    country_host: "MEX",
  },
  {
    match_number: 25,
    group_letter: "A",
    home_code: "cz",
    away_code: "za",
    match_date: localToUtcIso("2026-06-18", 15, 0, "EDT"),
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country_host: "USA",
  },
  {
    match_number: 28,
    group_letter: "A",
    home_code: "mx",
    away_code: "kr",
    match_date: localToUtcIso("2026-06-18", 21, 0, "MEX"),
    venue: "Estadio Akron",
    city: "Zapopan",
    country_host: "MEX",
  },
  {
    match_number: 53,
    group_letter: "A",
    home_code: "cz",
    away_code: "mx",
    match_date: localToUtcIso("2026-06-24", 15, 0, "MEX"),
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country_host: "MEX",
  },
  {
    match_number: 54,
    group_letter: "A",
    home_code: "za",
    away_code: "kr",
    match_date: localToUtcIso("2026-06-24", 18, 0, "MEX"),
    venue: "Estadio BBVA",
    city: "Guadalupe",
    country_host: "MEX",
  },
  // B
  {
    match_number: 3,
    group_letter: "B",
    home_code: "ca",
    away_code: "ba",
    match_date: localToUtcIso("2026-06-12", 15, 0, "EDT"),
    venue: "BMO Field",
    city: "Toronto",
    country_host: "CAN",
  },
  {
    match_number: 8,
    group_letter: "B",
    home_code: "qa",
    away_code: "ch",
    match_date: localToUtcIso("2026-06-13", 15, 0, "PDT"),
    venue: "Levi's Stadium",
    city: "Santa Clara",
    country_host: "USA",
  },
  {
    match_number: 26,
    group_letter: "B",
    home_code: "ch",
    away_code: "ba",
    match_date: localToUtcIso("2026-06-18", 15, 0, "PDT"),
    venue: "SoFi Stadium",
    city: "Inglewood",
    country_host: "USA",
  },
  {
    match_number: 27,
    group_letter: "B",
    home_code: "ca",
    away_code: "qa",
    match_date: localToUtcIso("2026-06-18", 18, 0, "PDT"),
    venue: "BC Place",
    city: "Vancouver",
    country_host: "CAN",
  },
  {
    match_number: 51,
    group_letter: "B",
    home_code: "ch",
    away_code: "ca",
    match_date: localToUtcIso("2026-06-24", 15, 0, "PDT"),
    venue: "BC Place",
    city: "Vancouver",
    country_host: "CAN",
  },
  {
    match_number: 52,
    group_letter: "B",
    home_code: "ba",
    away_code: "qa",
    match_date: localToUtcIso("2026-06-24", 18, 0, "PDT"),
    venue: "Lumen Field",
    city: "Seattle",
    country_host: "USA",
  },
  // C
  {
    match_number: 7,
    group_letter: "C",
    home_code: "br",
    away_code: "ma",
    match_date: localToUtcIso("2026-06-13", 18, 0, "EDT"),
    venue: "MetLife Stadium",
    city: "East Rutherford",
    country_host: "USA",
  },
  {
    match_number: 5,
    group_letter: "C",
    home_code: "ht",
    away_code: "gb-sct",
    match_date: localToUtcIso("2026-06-13", 21, 0, "EDT"),
    venue: "Gillette Stadium",
    city: "Foxborough",
    country_host: "USA",
  },
  {
    match_number: 30,
    group_letter: "C",
    home_code: "gb-sct",
    away_code: "ma",
    match_date: localToUtcIso("2026-06-19", 18, 0, "EDT"),
    venue: "Gillette Stadium",
    city: "Foxborough",
    country_host: "USA",
  },
  {
    match_number: 29,
    group_letter: "C",
    home_code: "br",
    away_code: "ht",
    match_date: localToUtcIso("2026-06-19", 20, 30, "EDT"),
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    country_host: "USA",
  },
  {
    match_number: 49,
    group_letter: "C",
    home_code: "gb-sct",
    away_code: "br",
    match_date: localToUtcIso("2026-06-24", 18, 0, "EDT"),
    venue: "Hard Rock Stadium",
    city: "Miami Gardens",
    country_host: "USA",
  },
  {
    match_number: 50,
    group_letter: "C",
    home_code: "ma",
    away_code: "ht",
    match_date: localToUtcIso("2026-06-24", 18, 0, "EDT"),
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country_host: "USA",
  },
  // D
  {
    match_number: 4,
    group_letter: "D",
    home_code: "us",
    away_code: "py",
    match_date: localToUtcIso("2026-06-12", 18, 0, "PDT"),
    venue: "SoFi Stadium",
    city: "Inglewood",
    country_host: "USA",
  },
  {
    match_number: 6,
    group_letter: "D",
    home_code: "au",
    away_code: "tr",
    match_date: localToUtcIso("2026-06-13", 21, 0, "PDT"),
    venue: "BC Place",
    city: "Vancouver",
    country_host: "CAN",
  },
  {
    match_number: 32,
    group_letter: "D",
    home_code: "us",
    away_code: "au",
    match_date: localToUtcIso("2026-06-19", 12, 0, "PDT"),
    venue: "Lumen Field",
    city: "Seattle",
    country_host: "USA",
  },
  {
    match_number: 31,
    group_letter: "D",
    home_code: "tr",
    away_code: "py",
    match_date: localToUtcIso("2026-06-19", 20, 0, "PDT"),
    venue: "Levi's Stadium",
    city: "Santa Clara",
    country_host: "USA",
  },
  {
    match_number: 59,
    group_letter: "D",
    home_code: "tr",
    away_code: "us",
    match_date: localToUtcIso("2026-06-25", 19, 0, "PDT"),
    venue: "SoFi Stadium",
    city: "Inglewood",
    country_host: "USA",
  },
  {
    match_number: 60,
    group_letter: "D",
    home_code: "py",
    away_code: "au",
    match_date: localToUtcIso("2026-06-25", 19, 0, "PDT"),
    venue: "Levi's Stadium",
    city: "Santa Clara",
    country_host: "USA",
  },
  // E
  {
    match_number: 10,
    group_letter: "E",
    home_code: "de",
    away_code: "cw",
    match_date: localToUtcIso("2026-06-14", 15, 0, "CDT"),
    venue: "NRG Stadium",
    city: "Houston",
    country_host: "USA",
  },
  {
    match_number: 9,
    group_letter: "E",
    home_code: "ci",
    away_code: "ec",
    match_date: localToUtcIso("2026-06-14", 18, 0, "EDT"),
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    country_host: "USA",
  },
  {
    match_number: 33,
    group_letter: "E",
    home_code: "de",
    away_code: "ci",
    match_date: localToUtcIso("2026-06-20", 15, 0, "EDT"),
    venue: "BMO Field",
    city: "Toronto",
    country_host: "CAN",
  },
  {
    match_number: 34,
    group_letter: "E",
    home_code: "ec",
    away_code: "cw",
    match_date: localToUtcIso("2026-06-20", 18, 0, "CDT"),
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country_host: "USA",
  },
  {
    match_number: 55,
    group_letter: "E",
    home_code: "cw",
    away_code: "ci",
    match_date: localToUtcIso("2026-06-25", 15, 0, "EDT"),
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    country_host: "USA",
  },
  {
    match_number: 56,
    group_letter: "E",
    home_code: "ec",
    away_code: "de",
    match_date: localToUtcIso("2026-06-25", 18, 0, "EDT"),
    venue: "MetLife Stadium",
    city: "East Rutherford",
    country_host: "USA",
  },
  // F
  {
    match_number: 11,
    group_letter: "F",
    home_code: "nl",
    away_code: "jp",
    match_date: localToUtcIso("2026-06-14", 15, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
  },
  {
    match_number: 12,
    group_letter: "F",
    home_code: "se",
    away_code: "tn",
    match_date: localToUtcIso("2026-06-14", 18, 0, "MEX"),
    venue: "Estadio BBVA",
    city: "Guadalupe",
    country_host: "MEX",
  },
  {
    match_number: 35,
    group_letter: "F",
    home_code: "nl",
    away_code: "se",
    match_date: localToUtcIso("2026-06-20", 15, 0, "CDT"),
    venue: "NRG Stadium",
    city: "Houston",
    country_host: "USA",
  },
  {
    match_number: 36,
    group_letter: "F",
    home_code: "tn",
    away_code: "jp",
    match_date: localToUtcIso("2026-06-20", 18, 0, "MEX"),
    venue: "Estadio BBVA",
    city: "Guadalupe",
    country_host: "MEX",
  },
  {
    match_number: 57,
    group_letter: "F",
    home_code: "jp",
    away_code: "se",
    match_date: localToUtcIso("2026-06-25", 15, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
  },
  {
    match_number: 58,
    group_letter: "F",
    home_code: "tn",
    away_code: "nl",
    match_date: localToUtcIso("2026-06-25", 18, 0, "CDT"),
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country_host: "USA",
  },
  // G
  {
    match_number: 16,
    group_letter: "G",
    home_code: "be",
    away_code: "eg",
    match_date: localToUtcIso("2026-06-15", 12, 0, "PDT"),
    venue: "Lumen Field",
    city: "Seattle",
    country_host: "USA",
  },
  {
    match_number: 15,
    group_letter: "G",
    home_code: "ir",
    away_code: "nz",
    match_date: localToUtcIso("2026-06-15", 18, 0, "PDT"),
    venue: "SoFi Stadium",
    city: "Inglewood",
    country_host: "USA",
  },
  {
    match_number: 39,
    group_letter: "G",
    home_code: "be",
    away_code: "ir",
    match_date: localToUtcIso("2026-06-21", 12, 0, "PDT"),
    venue: "SoFi Stadium",
    city: "Inglewood",
    country_host: "USA",
  },
  {
    match_number: 40,
    group_letter: "G",
    home_code: "nz",
    away_code: "eg",
    match_date: localToUtcIso("2026-06-21", 18, 0, "PDT"),
    venue: "BC Place",
    city: "Vancouver",
    country_host: "CAN",
  },
  {
    match_number: 63,
    group_letter: "G",
    home_code: "eg",
    away_code: "ir",
    match_date: localToUtcIso("2026-06-26", 20, 0, "PDT"),
    venue: "Lumen Field",
    city: "Seattle",
    country_host: "USA",
  },
  {
    match_number: 64,
    group_letter: "G",
    home_code: "nz",
    away_code: "be",
    match_date: localToUtcIso("2026-06-26", 20, 0, "PDT"),
    venue: "BC Place",
    city: "Vancouver",
    country_host: "CAN",
  },
  // H
  {
    match_number: 14,
    group_letter: "H",
    home_code: "es",
    away_code: "cv",
    match_date: localToUtcIso("2026-06-15", 15, 0, "EDT"),
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country_host: "USA",
  },
  {
    match_number: 13,
    group_letter: "H",
    home_code: "sa",
    away_code: "uy",
    match_date: localToUtcIso("2026-06-15", 18, 0, "EDT"),
    venue: "Hard Rock Stadium",
    city: "Miami Gardens",
    country_host: "USA",
  },
  {
    match_number: 38,
    group_letter: "H",
    home_code: "es",
    away_code: "sa",
    match_date: localToUtcIso("2026-06-21", 15, 0, "EDT"),
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country_host: "USA",
  },
  {
    match_number: 37,
    group_letter: "H",
    home_code: "uy",
    away_code: "cv",
    match_date: localToUtcIso("2026-06-21", 18, 0, "EDT"),
    venue: "Hard Rock Stadium",
    city: "Miami Gardens",
    country_host: "USA",
  },
  {
    match_number: 65,
    group_letter: "H",
    home_code: "cv",
    away_code: "sa",
    match_date: localToUtcIso("2026-06-26", 15, 0, "CDT"),
    venue: "NRG Stadium",
    city: "Houston",
    country_host: "USA",
  },
  {
    match_number: 66,
    group_letter: "H",
    home_code: "uy",
    away_code: "es",
    match_date: localToUtcIso("2026-06-26", 18, 0, "MEX"),
    venue: "Estadio Akron",
    city: "Zapopan",
    country_host: "MEX",
  },
  // I
  {
    match_number: 17,
    group_letter: "I",
    home_code: "fr",
    away_code: "sn",
    match_date: localToUtcIso("2026-06-16", 15, 0, "EDT"),
    venue: "MetLife Stadium",
    city: "East Rutherford",
    country_host: "USA",
  },
  {
    match_number: 18,
    group_letter: "I",
    home_code: "iq",
    away_code: "no",
    match_date: localToUtcIso("2026-06-16", 18, 0, "EDT"),
    venue: "Gillette Stadium",
    city: "Foxborough",
    country_host: "USA",
  },
  {
    match_number: 42,
    group_letter: "I",
    home_code: "fr",
    away_code: "iq",
    match_date: localToUtcIso("2026-06-22", 17, 0, "EDT"),
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    country_host: "USA",
  },
  {
    match_number: 41,
    group_letter: "I",
    home_code: "no",
    away_code: "sn",
    match_date: localToUtcIso("2026-06-22", 20, 0, "EDT"),
    venue: "MetLife Stadium",
    city: "East Rutherford",
    country_host: "USA",
  },
  {
    match_number: 61,
    group_letter: "I",
    home_code: "no",
    away_code: "fr",
    match_date: localToUtcIso("2026-06-26", 15, 0, "EDT"),
    venue: "Gillette Stadium",
    city: "Foxborough",
    country_host: "USA",
  },
  {
    match_number: 62,
    group_letter: "I",
    home_code: "sn",
    away_code: "iq",
    match_date: localToUtcIso("2026-06-26", 15, 0, "EDT"),
    venue: "BMO Field",
    city: "Toronto",
    country_host: "CAN",
  },
  // J
  {
    match_number: 19,
    group_letter: "J",
    home_code: "ar",
    away_code: "dz",
    match_date: localToUtcIso("2026-06-16", 15, 0, "CDT"),
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country_host: "USA",
  },
  {
    match_number: 20,
    group_letter: "J",
    home_code: "at",
    away_code: "jo",
    match_date: localToUtcIso("2026-06-16", 18, 0, "PDT"),
    venue: "Levi's Stadium",
    city: "Santa Clara",
    country_host: "USA",
  },
  {
    match_number: 43,
    group_letter: "J",
    home_code: "ar",
    away_code: "at",
    match_date: localToUtcIso("2026-06-22", 15, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
  },
  {
    match_number: 44,
    group_letter: "J",
    home_code: "jo",
    away_code: "dz",
    match_date: localToUtcIso("2026-06-22", 18, 0, "PDT"),
    venue: "Levi's Stadium",
    city: "Santa Clara",
    country_host: "USA",
  },
  {
    match_number: 69,
    group_letter: "J",
    home_code: "dz",
    away_code: "at",
    match_date: localToUtcIso("2026-06-27", 15, 0, "CDT"),
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country_host: "USA",
  },
  {
    match_number: 70,
    group_letter: "J",
    home_code: "jo",
    away_code: "ar",
    match_date: localToUtcIso("2026-06-27", 18, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
  },
  // K
  {
    match_number: 23,
    group_letter: "K",
    home_code: "pt",
    away_code: "cd",
    match_date: localToUtcIso("2026-06-17", 15, 0, "CDT"),
    venue: "NRG Stadium",
    city: "Houston",
    country_host: "USA",
  },
  {
    match_number: 24,
    group_letter: "K",
    home_code: "uz",
    away_code: "co",
    match_date: localToUtcIso("2026-06-17", 18, 0, "MEX"),
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country_host: "MEX",
  },
  {
    match_number: 47,
    group_letter: "K",
    home_code: "pt",
    away_code: "uz",
    match_date: localToUtcIso("2026-06-23", 15, 0, "CDT"),
    venue: "NRG Stadium",
    city: "Houston",
    country_host: "USA",
  },
  {
    match_number: 48,
    group_letter: "K",
    home_code: "co",
    away_code: "cd",
    match_date: localToUtcIso("2026-06-23", 18, 0, "MEX"),
    venue: "Estadio Akron",
    city: "Zapopan",
    country_host: "MEX",
  },
  {
    match_number: 71,
    group_letter: "K",
    home_code: "co",
    away_code: "pt",
    match_date: localToUtcIso("2026-06-27", 15, 0, "EDT"),
    venue: "Hard Rock Stadium",
    city: "Miami Gardens",
    country_host: "USA",
  },
  {
    match_number: 72,
    group_letter: "K",
    home_code: "cd",
    away_code: "uz",
    match_date: localToUtcIso("2026-06-27", 18, 0, "EDT"),
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country_host: "USA",
  },
  // L
  {
    match_number: 22,
    group_letter: "L",
    home_code: "gb-eng",
    away_code: "hr",
    match_date: localToUtcIso("2026-06-17", 15, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
  },
  {
    match_number: 21,
    group_letter: "L",
    home_code: "gh",
    away_code: "pa",
    match_date: localToUtcIso("2026-06-17", 18, 0, "EDT"),
    venue: "BMO Field",
    city: "Toronto",
    country_host: "CAN",
  },
  {
    match_number: 45,
    group_letter: "L",
    home_code: "gb-eng",
    away_code: "gh",
    match_date: localToUtcIso("2026-06-23", 15, 0, "EDT"),
    venue: "Gillette Stadium",
    city: "Foxborough",
    country_host: "USA",
  },
  {
    match_number: 46,
    group_letter: "L",
    home_code: "pa",
    away_code: "hr",
    match_date: localToUtcIso("2026-06-23", 18, 0, "EDT"),
    venue: "BMO Field",
    city: "Toronto",
    country_host: "CAN",
  },
  {
    match_number: 67,
    group_letter: "L",
    home_code: "pa",
    away_code: "gb-eng",
    match_date: localToUtcIso("2026-06-27", 15, 0, "EDT"),
    venue: "MetLife Stadium",
    city: "East Rutherford",
    country_host: "USA",
  },
  {
    match_number: 68,
    group_letter: "L",
    home_code: "hr",
    away_code: "gh",
    match_date: localToUtcIso("2026-06-27", 18, 0, "EDT"),
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    country_host: "USA",
  },
];

export type KnockMatchDef = {
  match_number: number;
  phase_slug: string;
  match_date: string;
  venue: string;
  city: string;
  country_host: HostCountry;
  elimination_slot_label: string;
};

export const WC2026_KNOCKOUT_MATCHES: KnockMatchDef[] = [
  {
    match_number: 73,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-06-28", 15, 0, "PDT"),
    venue: "SoFi Stadium",
    city: "Inglewood",
    country_host: "USA",
    elimination_slot_label: "2º Grupo A vs 2º Grupo B",
  },
  {
    match_number: 76,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-06-29", 15, 0, "CDT"),
    venue: "NRG Stadium",
    city: "Houston",
    country_host: "USA",
    elimination_slot_label: "1º Grupo C vs 2º Grupo F",
  },
  {
    match_number: 74,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-06-29", 15, 0, "EDT"),
    venue: "Gillette Stadium",
    city: "Foxborough",
    country_host: "USA",
    elimination_slot_label: "1º Grupo E vs 3º (A/B/C/D/F)",
  },
  {
    match_number: 75,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-06-29", 18, 0, "MEX"),
    venue: "Estadio BBVA",
    city: "Guadalupe",
    country_host: "MEX",
    elimination_slot_label: "1º Grupo F vs 2º Grupo C",
  },
  {
    match_number: 78,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-06-30", 15, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
    elimination_slot_label: "2º Grupo E vs 2º Grupo I",
  },
  {
    match_number: 77,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-06-30", 15, 0, "EDT"),
    venue: "MetLife Stadium",
    city: "East Rutherford",
    country_host: "USA",
    elimination_slot_label: "1º Grupo I vs 3º (C/D/F/G/H)",
  },
  {
    match_number: 79,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-06-30", 18, 0, "MEX"),
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country_host: "MEX",
    elimination_slot_label: "1º Grupo A vs 3º (C/E/F/H/I)",
  },
  {
    match_number: 80,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-01", 15, 0, "EDT"),
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country_host: "USA",
    elimination_slot_label: "1º Grupo L vs 3º (E/H/I/J/K)",
  },
  {
    match_number: 82,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-01", 15, 0, "PDT"),
    venue: "Lumen Field",
    city: "Seattle",
    country_host: "USA",
    elimination_slot_label: "1º Grupo G vs 3º (A/E/H/I/J)",
  },
  {
    match_number: 81,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-01", 18, 0, "PDT"),
    venue: "Levi's Stadium",
    city: "Santa Clara",
    country_host: "USA",
    elimination_slot_label: "1º Grupo D vs 3º (B/E/F/I/J)",
  },
  {
    match_number: 84,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-02", 15, 0, "PDT"),
    venue: "SoFi Stadium",
    city: "Inglewood",
    country_host: "USA",
    elimination_slot_label: "1º Grupo H vs 2º Grupo J",
  },
  {
    match_number: 83,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-02", 15, 0, "EDT"),
    venue: "BMO Field",
    city: "Toronto",
    country_host: "CAN",
    elimination_slot_label: "2º Grupo K vs 2º Grupo L",
  },
  {
    match_number: 85,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-02", 18, 0, "PDT"),
    venue: "BC Place",
    city: "Vancouver",
    country_host: "CAN",
    elimination_slot_label: "1º Grupo B vs 3º (E/F/G/I/J)",
  },
  {
    match_number: 88,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-03", 15, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
    elimination_slot_label: "2º Grupo D vs 2º Grupo G",
  },
  {
    match_number: 86,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-03", 15, 0, "EDT"),
    venue: "Hard Rock Stadium",
    city: "Miami Gardens",
    country_host: "USA",
    elimination_slot_label: "1º Grupo J vs 2º Grupo H",
  },
  {
    match_number: 87,
    phase_slug: "round_of_32",
    match_date: localToUtcIso("2026-07-03", 18, 0, "CDT"),
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country_host: "USA",
    elimination_slot_label: "1º Grupo K vs 3º (D/E/I/J/L)",
  },
  {
    match_number: 90,
    phase_slug: "round_of_16",
    match_date: localToUtcIso("2026-07-04", 15, 0, "CDT"),
    venue: "NRG Stadium",
    city: "Houston",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 73 vs Ganador partido 75",
  },
  {
    match_number: 89,
    phase_slug: "round_of_16",
    match_date: localToUtcIso("2026-07-04", 15, 0, "EDT"),
    venue: "Lincoln Financial Field",
    city: "Philadelphia",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 74 vs Ganador partido 77",
  },
  {
    match_number: 91,
    phase_slug: "round_of_16",
    match_date: localToUtcIso("2026-07-05", 15, 0, "EDT"),
    venue: "MetLife Stadium",
    city: "East Rutherford",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 76 vs Ganador partido 78",
  },
  {
    match_number: 92,
    phase_slug: "round_of_16",
    match_date: localToUtcIso("2026-07-05", 18, 0, "MEX"),
    venue: "Estadio Azteca",
    city: "Ciudad de México",
    country_host: "MEX",
    elimination_slot_label: "Ganador partido 79 vs Ganador partido 80",
  },
  {
    match_number: 93,
    phase_slug: "round_of_16",
    match_date: localToUtcIso("2026-07-06", 15, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 83 vs Ganador partido 84",
  },
  {
    match_number: 94,
    phase_slug: "round_of_16",
    match_date: localToUtcIso("2026-07-06", 15, 0, "PDT"),
    venue: "Lumen Field",
    city: "Seattle",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 81 vs Ganador partido 82",
  },
  {
    match_number: 95,
    phase_slug: "round_of_16",
    match_date: localToUtcIso("2026-07-07", 15, 0, "EDT"),
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 86 vs Ganador partido 88",
  },
  {
    match_number: 96,
    phase_slug: "round_of_16",
    match_date: localToUtcIso("2026-07-07", 15, 0, "PDT"),
    venue: "BC Place",
    city: "Vancouver",
    country_host: "CAN",
    elimination_slot_label: "Ganador partido 85 vs Ganador partido 87",
  },
  {
    match_number: 97,
    phase_slug: "quarterfinals",
    match_date: localToUtcIso("2026-07-09", 15, 0, "EDT"),
    venue: "Gillette Stadium",
    city: "Foxborough",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 89 vs Ganador partido 90",
  },
  {
    match_number: 98,
    phase_slug: "quarterfinals",
    match_date: localToUtcIso("2026-07-10", 15, 0, "PDT"),
    venue: "SoFi Stadium",
    city: "Inglewood",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 93 vs Ganador partido 94",
  },
  {
    match_number: 99,
    phase_slug: "quarterfinals",
    match_date: localToUtcIso("2026-07-11", 15, 0, "EDT"),
    venue: "Hard Rock Stadium",
    city: "Miami Gardens",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 91 vs Ganador partido 92",
  },
  {
    match_number: 100,
    phase_slug: "quarterfinals",
    match_date: localToUtcIso("2026-07-11", 15, 0, "CDT"),
    venue: "Arrowhead Stadium",
    city: "Kansas City",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 95 vs Ganador partido 96",
  },
  {
    match_number: 101,
    phase_slug: "semifinals",
    match_date: localToUtcIso("2026-07-14", 15, 0, "CDT"),
    venue: "AT&T Stadium",
    city: "Arlington",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 97 vs Ganador partido 98",
  },
  {
    match_number: 102,
    phase_slug: "semifinals",
    match_date: localToUtcIso("2026-07-15", 15, 0, "EDT"),
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 99 vs Ganador partido 100",
  },
  {
    match_number: 103,
    phase_slug: "third_place",
    match_date: localToUtcIso("2026-07-18", 15, 0, "EDT"),
    venue: "Hard Rock Stadium",
    city: "Miami Gardens",
    country_host: "USA",
    elimination_slot_label: "Perdedor partido 101 vs Perdedor partido 102",
  },
  {
    match_number: 104,
    phase_slug: "final",
    match_date: localToUtcIso("2026-07-19", 15, 0, "EDT"),
    venue: "MetLife Stadium",
    city: "East Rutherford",
    country_host: "USA",
    elimination_slot_label: "Ganador partido 101 vs Ganador partido 102",
  },
];
